# Generated by Django 3.1.1 on 2020-09-17 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bricks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 7, 26, 5, 544235)),
        ),
    ]
