# Generated by Django 3.1.1 on 2020-09-17 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0002_bricks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bricks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 7, 42, 35, 268250)),
        ),
    ]
